Move config and dependencies out of mockui
Selenium cannot be removed from integration-tests-common because weird things happen (java.lang.NoClassDefFoundError: org/json/JSONObject)